package com.njzhikejia.echohealth.healthlife.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.njzhikejia.echohealth.healthlife.entity.Message;
import com.njzhikejia.echohealth.healthlife.entity.Extend;
import com.njzhikejia.echohealth.healthlife.entity.User;
import com.njzhikejia.echohealth.healthlife.entity.Concerns;
import com.njzhikejia.echohealth.healthlife.entity.Concerneds;
import com.njzhikejia.echohealth.healthlife.entity.SpecificData;

import com.njzhikejia.echohealth.healthlife.greendao.MessageDao;
import com.njzhikejia.echohealth.healthlife.greendao.ExtendDao;
import com.njzhikejia.echohealth.healthlife.greendao.UserDao;
import com.njzhikejia.echohealth.healthlife.greendao.ConcernsDao;
import com.njzhikejia.echohealth.healthlife.greendao.ConcernedsDao;
import com.njzhikejia.echohealth.healthlife.greendao.SpecificDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageDaoConfig;
    private final DaoConfig extendDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig concernsDaoConfig;
    private final DaoConfig concernedsDaoConfig;
    private final DaoConfig specificDataDaoConfig;

    private final MessageDao messageDao;
    private final ExtendDao extendDao;
    private final UserDao userDao;
    private final ConcernsDao concernsDao;
    private final ConcernedsDao concernedsDao;
    private final SpecificDataDao specificDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        extendDaoConfig = daoConfigMap.get(ExtendDao.class).clone();
        extendDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        concernsDaoConfig = daoConfigMap.get(ConcernsDao.class).clone();
        concernsDaoConfig.initIdentityScope(type);

        concernedsDaoConfig = daoConfigMap.get(ConcernedsDao.class).clone();
        concernedsDaoConfig.initIdentityScope(type);

        specificDataDaoConfig = daoConfigMap.get(SpecificDataDao.class).clone();
        specificDataDaoConfig.initIdentityScope(type);

        messageDao = new MessageDao(messageDaoConfig, this);
        extendDao = new ExtendDao(extendDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        concernsDao = new ConcernsDao(concernsDaoConfig, this);
        concernedsDao = new ConcernedsDao(concernedsDaoConfig, this);
        specificDataDao = new SpecificDataDao(specificDataDaoConfig, this);

        registerDao(Message.class, messageDao);
        registerDao(Extend.class, extendDao);
        registerDao(User.class, userDao);
        registerDao(Concerns.class, concernsDao);
        registerDao(Concerneds.class, concernedsDao);
        registerDao(SpecificData.class, specificDataDao);
    }
    
    public void clear() {
        messageDaoConfig.clearIdentityScope();
        extendDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        concernsDaoConfig.clearIdentityScope();
        concernedsDaoConfig.clearIdentityScope();
        specificDataDaoConfig.clearIdentityScope();
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public ExtendDao getExtendDao() {
        return extendDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ConcernsDao getConcernsDao() {
        return concernsDao;
    }

    public ConcernedsDao getConcernedsDao() {
        return concernedsDao;
    }

    public SpecificDataDao getSpecificDataDao() {
        return specificDataDao;
    }

}
